cp -f "../Client/bin/Debug/net8.0/ToSic.Module.PageTemplates.Client.Oqtane.dll" "../../../oqtane.framework/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Client/bin/Debug/net8.0/ToSic.Module.PageTemplates.Client.Oqtane.pdb" "../../../oqtane.framework/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Server/bin/Debug/net8.0/ToSic.Module.PageTemplates.Server.Oqtane.dll" "../../../oqtane.framework/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Server/bin/Debug/net8.0/ToSic.Module.PageTemplates.Server.Oqtane.pdb" "../../../oqtane.framework/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Shared/bin/Debug/net8.0/ToSic.Module.PageTemplates.Shared.Oqtane.dll" "../../../oqtane.framework/Oqtane.Server/bin/Debug/net8.0/"
cp -f "../Shared/bin/Debug/net8.0/ToSic.Module.PageTemplates.Shared.Oqtane.pdb" "../../../oqtane.framework/Oqtane.Server/bin/Debug/net8.0/"
cp -rf "../Server/wwwroot/"* "../../../oqtane.framework/Oqtane.Server/wwwroot/"
